export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';
export const FILTER_SERVICE = 'FILTER_SERVICE';

